# 起動時読み込みプラグイン


# 初期からのやつ
[[plugins]]
repo = 'Shougo/dein.vim'

# カラースキーマ
#[[plugins]]
#repo = "tomasr/molokai"
#hook_add = 'let g:molokai_original = 1'
[[plugins]]
repo = 'Haron-Prime/Antares'
hook_add = '''
colorscheme Antares
'''

# ステータスバー
[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
	" モードの表示名を定義(デフォルトだと長くて横幅を圧迫するので略称にしている)
	let g:airline_mode_map = {
    				\ '__' : '-',
    				\ 'n'  : 'N',
    				\ 'i'  : 'I',
    				\ 'R'  : 'R',
    				\ 'c'  : 'C',
    				\ 'v'  : 'V',
    				\ 'V'  : 'V',
    				\ '' : '',
    				\ 's'  : 'S',
    				\ 'S'  : 'S',
    				\ }
	" パワーラインでかっこよく
	let g:airline_powerline_fonts = 1
	" カラーテーマ指定してかっこよく
	let g:airline_theme = 'badwolf'
	" タブバーをかっこよく
	let g:airline#extensions#tabline#enabled = 1
	" 選択行列の表示をカスタム(デフォルトだと長くて横幅を圧迫するので最小限に)
	let g:airline_section_z = airline#section#create(['windowswap', '%3p%% ', 'linenr', ':%3v'])
	" virtulenvを認識しているか確認用に、現在activateされているvirtualenvを表示(vim-virtualenvの拡張)
	let g:airline#extensions#virtualenv#enabled = 1
	" gitのHEADから変更した行の+-を非表示(vim-gitgutterの拡張)
	let g:airline#extensions#hunks#enabled = 0

	" Lintツールによるエラー、警告を表示(ALEの拡張)
	let g:airline#extensions#ale#enabled = 1
	let g:airline#extensions#ale#error_symbol = 'E:'
	let g:airline#extensions#ale#warning_symbol = 'W:'
'''
depends = ['vim-airline-themes']

# 依存関係を指定したからと言って、自動でインストールはされない（ここは NeoBundle と違う）
[[plugins]]
repo = 'vim-airline/vim-airline-themes'


# ファイルマネージャ
[[plugins]]
repo = 'Shougo/denite.nvim'
hook_post_source = '''
	call denite#custom#var('file_rec', 'command', ['ag', '--follow', '--nocolor', '--nogroup', '-g', ''])
	call denite#custom#var('grep', 'command', ['ag'])
	call denite#custom#var('grep', 'recursive_opts', [])
	call denite#custom#var('grep', 'pattern_opt', [])
	call denite#custom#var('grep', 'default_opts', ['--follow', '--no-group', '--no-color'])
'''
